# Some practices done in this file is not suitable for production environmnents or can cause bugs
# The main reason to change the standard way is to make container node_modules available for host
# this way vscode intellisense works correctly
FROM node:12

EXPOSE 3333 9229 9230

WORKDIR /usr/app
COPY package.json yarn.lock ./

COPY . .

CMD yarn && yarn prisma:generate && yarn prisma:migrate && yarn dev
