FROM node:13

# Create app folder
WORKDIR /usr/app

# Workaround to Error: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
RUN apt-get update
RUN apt-get install musl-dev openssl -y
RUN ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1

# Copy package.json
COPY package*.json prisma ./

# Install dependencies
RUN npm install

# Copy other files
COPY . .

RUN npm run prisma:generate
