FROM node:12-alpine

# Create app folder
WORKDIR /usr/app

# Copy package.json and yarn.lock
COPY ./package.json .
COPY ./yarn.lock .

# Install dependencies
RUN yarn --only=production

# Copy dist and prisma files
COPY ./dist .

# Generate migrations
RUN yarn prisma:generate

EXPOSE 3333

CMD ["yarn", "start"]
